In [22]:
import pandas as pd
import numpy as np

In [23]:
import warnings
warnings.filterwarnings('ignore')
pd.set_option('max_column', None)
db = pd.read_csv('../data/Week1_challenge_data_source(CSV).csv', na_values=['?', None])
db.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),Avg Bearer TP UL (kbps),TCP DL Retrans. Vol (Bytes),TCP UL Retrans. Vol (Bytes),DL TP < 50 Kbps (%),50 Kbps < DL TP < 250 Kbps (%),250 Kbps < DL TP < 1 Mbps (%),DL TP > 1 Mbps (%),UL TP < 10 Kbps (%),10 Kbps < UL TP < 50 Kbps (%),50 Kbps < UL TP < 300 Kbps (%),UL TP > 300 Kbps (%),HTTP DL (Bytes),HTTP UL (Bytes),Activity Duration DL (ms),Activity Duration UL (ms),Dur. (ms).1,Handset Manufacturer,Handset Type,Nb of sec with 125000B < Vol DL,Nb of sec with 1250B < Vol UL < 6250B,Nb of sec with 31250B < Vol DL < 125000B,Nb of sec with 37500B < Vol UL,Nb of sec with 6250B < Vol DL < 31250B,Nb of sec with 6250B < Vol UL < 37500B,Nb of sec with Vol DL < 6250B,Nb of sec with Vol UL < 1250B,Social Media DL (Bytes),Social Media UL (Bytes),Google DL (Bytes),Google UL (Bytes),Email DL (Bytes),Email UL (Bytes),Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,42.0,5.0,23.0,44.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,37624.0,38787.0,1.823653e+09,Samsung,Samsung Galaxy A5 Sm-A520F,NaN,NaN,NaN,NaN,NaN,NaN,213.0,214.0,1545765.0,24420.0,1634479.0,1271433.0,3563542.0,137762.0,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,65.0,5.0,16.0,26.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,168.0,3560.0,1.365104e+09,Samsung,Samsung Galaxy J5 (Sm-J530),NaN,NaN,NaN,NaN,NaN,NaN,971.0,1022.0,1926113.0,7165.0,3493924.0,920172.0,629046.0,308339.0,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,NaN,NaN,6.0,9.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,1.361763e+09,Samsung,Samsung Galaxy A8 (2018),NaN,NaN,NaN,NaN,NaN,NaN,751.0,695.0,1684053.0,42224.0,8535055.0,1694064.0,2690151.0,672973.0,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,NaN,NaN,44.0,44.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,3330.0,37882.0,1.321510e+09,undefined,undefined,NaN,NaN,NaN,NaN,NaN,NaN,17.0,207.0,644121.0,13372.0,9023734.0,2788027.0,1439754.0,631229.0,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,NaN,NaN,6.0,9.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,1.089009e+09,Samsung,Samsung Sm-G390F,NaN,NaN,NaN,NaN,NaN,NaN,607.0,604.0,862600.0,50188.0,6248284.0,1500559.0,1936496.0,173853.0,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

In [24]:
db.columns.tolist()

['Bearer Id',
 'Start',
 'Start ms',
 'End',
 'End ms',
 'Dur. (ms)',
 'IMSI',
 'MSISDN/Number',
 'IMEI',
 'Last Location Name',
 'Avg RTT DL (ms)',
 'Avg RTT UL (ms)',
 'Avg Bearer TP DL (kbps)',
 'Avg Bearer TP UL (kbps)',
 'TCP DL Retrans. Vol (Bytes)',
 'TCP UL Retrans. Vol (Bytes)',
 'DL TP < 50 Kbps (%)',
 '50 Kbps < DL TP < 250 Kbps (%)',
 '250 Kbps < DL TP < 1 Mbps (%)',
 'DL TP > 1 Mbps (%)',
 'UL TP < 10 Kbps (%)',
 '10 Kbps < UL TP < 50 Kbps (%)',
 '50 Kbps < UL TP < 300 Kbps (%)',
 'UL TP > 300 Kbps (%)',
 'HTTP DL (Bytes)',
 'HTTP UL (Bytes)',
 'Activity Duration DL (ms)',
 'Activity Duration UL (ms)',
 'Dur. (ms).1',
 'Handset Manufacturer',
 'Handset Type',
 'Nb of sec with 125000B < Vol DL',
 'Nb of sec with 1250B < Vol UL < 6250B',
 'Nb of sec with 31250B < Vol DL < 125000B',
 'Nb of sec with 37500B < Vol UL',
 'Nb of sec with 6250B < Vol DL < 31250B',
 'Nb of sec with 6250B < Vol UL < 37500B',
 'Nb of sec with Vol DL < 6250B',
 'Nb of sec with Vol UL < 1250B',
 'Social Media DL (Bytes)',
 'Social Media UL (Bytes)',
 'Google DL (Bytes)',
 'Google UL (Bytes)',
 'Email DL (Bytes)',
 'Email UL (Bytes)',
 'Youtube DL (Bytes)',
 'Youtube UL (Bytes)',
 'Netflix DL (Bytes)',
 'Netflix UL (Bytes)',
 'Gaming DL (Bytes)',
 'Gaming UL (Bytes)',
 'Other DL (Bytes)',
 'Other UL (Bytes)',
 'Total UL (Bytes)',
 'Total DL (Bytes)']

In [25]:
print(f" There are {db.shape[0]} rows and {db.shape[1]} columns")

 There are 150001 rows and 55 columns

In [26]:
def percent_missing(df):
    
     # Calculate total number of cells in dataframe
    totalCells = np.product(df.shape)
    
    # Count number of missing values per column
    missingCount = df.isnull().sum()
    
     # Calculate total number of missing values
    totalMissing = missingCount.sum()
    
     # Calculate percentage of missing values
    print("The dataset contains", round(((totalMissing/totalCells) * 100), 2), "%", "missing values.")
    
percent_missing(db)

The dataset contains 12.5 % missing values.

In [27]:
db.isna().sum()

Bearer Id                                      991
Start                                            1
Start ms                                         1
End                                              1
End ms                                           1
Dur. (ms)                                        1
IMSI                                           570
MSISDN/Number                                 1066
IMEI                                           572
Last Location Name                            1153
Avg RTT DL (ms)                              27829
Avg RTT UL (ms)                              27812
Avg Bearer TP DL (kbps)                          1
Avg Bearer TP UL (kbps)                          1
TCP DL Retrans. Vol (Bytes)                  88146
TCP UL Retrans. Vol (Bytes)                  96649
DL TP < 50 Kbps (%)                            754
50 Kbps < DL TP < 250 Kbps (%)                 754
250 Kbps < DL TP < 1 Mbps (%)                  754
DL TP > 1 Mbps (%)                             754
UL TP < 10 Kbps (%)                            792
10 Kbps < UL TP < 50 Kbps (%)                  792
50 Kbps < UL TP < 300 Kbps (%)                 792
UL TP > 300 Kbps (%)                           792
HTTP DL (Bytes)                              81474
HTTP UL (Bytes)                              81810
Activity Duration DL (ms)                        1
Activity Duration UL (ms)                        1
Dur. (ms).1                                      1
Handset Manufacturer                           572
Handset Type                                   572
Nb of sec with 125000B < Vol DL              97538
Nb of sec with 1250B < Vol UL < 6250B        92894
Nb of sec with 31250B < Vol DL < 125000B     93586
Nb of sec with 37500B < Vol UL              130254
Nb of sec with 6250B < Vol DL < 31250B       88317
Nb of sec with 6250B < Vol UL < 37500B      111843
Nb of sec with Vol DL < 6250B                  755
Nb of sec with Vol UL < 1250B                  793
Social Media DL (Bytes)                          0
Social Media UL (Bytes)                          0
Google DL (Bytes)                                0
Google UL (Bytes)                                0
Email DL (Bytes)                                 0
Email UL (Bytes)                                 0
Youtube DL (Bytes)                               0
Youtube UL (Bytes)                               0
Netflix DL (Bytes)                               0
Netflix UL (Bytes)                               0
Gaming DL (Bytes)                                0
Gaming UL (Bytes)                                0
Other DL (Bytes)                                 0
Other UL (Bytes)                                 0
Total UL (Bytes)                                 1
Total DL (Bytes)                                 1
dtype: int64

In [28]:
# drop columns with more than 50% missing values
db_clean = db.dropna(axis=1, thresh = int(0.5*db.shape[0]), inplace=True)
db.shape

(150001, 45)

In [11]:
db.isna().sum()

Bearer Id                           991
Start                                 1
Start ms                              1
End                                   1
End ms                                1
Dur. (ms)                             1
IMSI                                570
MSISDN/Number                      1066
IMEI                                572
Last Location Name                 1153
Avg RTT DL (ms)                   27829
Avg RTT UL (ms)                   27812
Avg Bearer TP DL (kbps)               1
Avg Bearer TP UL (kbps)               1
DL TP < 50 Kbps (%)                 754
50 Kbps < DL TP < 250 Kbps (%)      754
250 Kbps < DL TP < 1 Mbps (%)       754
DL TP > 1 Mbps (%)                  754
UL TP < 10 Kbps (%)                 792
10 Kbps < UL TP < 50 Kbps (%)       792
50 Kbps < UL TP < 300 Kbps (%)      792
UL TP > 300 Kbps (%)                792
Activity Duration DL (ms)             1
Activity Duration UL (ms)             1
Dur. (ms).1                           1
Handset Manufacturer                572
Handset Type                        572
Nb of sec with Vol DL < 6250B       755
Nb of sec with Vol UL < 1250B       793
Social Media DL (Bytes)               0
Social Media UL (Bytes)               0
Google DL (Bytes)                     0
Google UL (Bytes)                     0
Email DL (Bytes)                      0
Email UL (Bytes)                      0
Youtube DL (Bytes)                    0
Youtube UL (Bytes)                    0
Netflix DL (Bytes)                    0
Netflix UL (Bytes)                    0
Gaming DL (Bytes)                     0
Gaming UL (Bytes)                     0
Other DL (Bytes)                      0
Other UL (Bytes)                      0
Total UL (Bytes)                      1
Total DL (Bytes)                      1
dtype: int64

In [29]:
db.describe()

,Bearer Id,Start ms,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),Avg Bearer TP UL (kbps),DL TP < 50 Kbps (%),50 Kbps < DL TP < 250 Kbps (%),250 Kbps < DL TP < 1 Mbps (%),DL TP > 1 Mbps (%),UL TP < 10 Kbps (%),10 Kbps < UL TP < 50 Kbps (%),50 Kbps < UL TP < 300 Kbps (%),UL TP > 300 Kbps (%),Activity Duration DL (ms),Activity Duration UL (ms),Dur. (ms).1,Nb of sec with Vol DL < 6250B,Nb of sec with Vol UL < 1250B,Social Media DL (Bytes),Social Media UL (Bytes),Google DL (Bytes),Google UL (Bytes),Email DL (Bytes),Email UL (Bytes),Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
count,1.490100e+05,150000.000000,150000.000000,1.500000e+05,1.494310e+05,1.489350e+05,1.494290e+05,122172.000000,122189.000000,150000.000000,150000.000000,149247.000000,149247.000000,149247.000000,149247.000000,149209.000000,149209.000000,149209.000000,149209.000000,1.500000e+05,1.500000e+05,1.500000e+05,149246.000000,149208.000000,1.500010e+05,150001.000000,1.500010e+05,1.500010e+05,1.500010e+05,150001.000000,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500000e+05,1.500000e+05
mean,1.013887e+19,499.188200,498.800880,1.046086e+05,2.082016e+14,4.188282e+10,4.847455e+13,109.795706,17.662883,13300.045927,1770.428647,92.844754,3.069355,1.717341,1.609654,98.530142,0.776749,0.147987,0.078923,1.829177e+06,1.408880e+06,1.046091e+08,3719.787552,4022.083454,1.795322e+06,32928.434380,5.750753e+06,2.056542e+06,1.791729e+06,467373.441940,1.163407e+07,1.100941e+07,1.162685e+07,1.100175e+07,4.220447e+08,8.288398e+06,4.211005e+08,8.264799e+06,4.112121e+07,4.546434e+08
std,2.893173e+18,288.611834,288.097653,8.103762e+04,2.148809e+10,2.447443e+12,2.241637e+13,619.782739,84.793524,23971.878541,4625.355500,13.038031,6.215233,4.159538,4.828890,4.634285,3.225176,1.624523,1.295396,5.696395e+06,4.643231e+06,8.103761e+07,9171.609010,10160.324314,1.035482e+06,19006.178256,3.309097e+06,1.189917e+06,1.035840e+06,269969.307031,6.710569e+06,6.345423e+06,6.725218e+06,6.359490e+06,2.439675e+08,4.782700e+06,2.432050e+08,4.769004e+06,1.127639e+07,2.441429e+08
min,6.917538e+18,0.000000,0.000000,7.142000e+03,2.040471e+14,3.360100e+10,4.400152e+11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,7.142988e+06,1.000000,1.000000,1.200000e+01,0.000000,2.070000e+02,3.000000e+00,1.400000e+01,2.000000,5.300000e+01,1.050000e+02,4.200000e+01,3.500000e+01,2.516000e+03,5.900000e+01,3.290000e+03,1.480000e+02,2.866892e+06,7.114041e+06
25%,7.349883e+18,250.000000,251.000000,5.744050e+04,2.082014e+14,3.365130e+10,3.546071e+13,32.000000,2.000000,43.000000,47.000000,91.000000,0.000000,0.000000,0.000000,99.000000,0.000000,0.000000,0.000000,1.487775e+04,2.153975e+04,5.744079e+07,87.000000,106.000000,8.991480e+05,16448.000000,2.882393e+06,1.024279e+06,8.927930e+05,233383.000000,5.833501e+06,5.517965e+06,5.777156e+06,5.475981e+06,2.104733e+08,4.128476e+06,2.101869e+08,4.145943e+06,3.322201e+07,2.431068e+08
50%,7.349883e+18,499.000000,500.000000,8.639900e+04,2.082015e+14,3.366371e+10,3.572201e+13,45.000000,5.000000,63.000000,63.000000,100.000000,0.000000,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000,3.930450e+04,4.679350e+04,8.639998e+07,203.000000,217.000000,1.794369e+06,32920.000000,5.765829e+06,2.054573e+06,1.793505e+06,466250.000000,1.161602e+07,1.101345e+07,1.164222e+07,1.099638e+07,4.234081e+08,8.291208e+06,4.218030e+08,8.267071e+06,4.114331e+07,4.558411e+08
75%,1.304243e+19,749.000000,750.000000,1.324302e+05,2.082018e+14,3.368349e+10,8.611970e+13,70.000000,15.000000,19710.750000,1120.000000,100.000000,4.000000,1.000000,0.000000,100.000000,0.000000,0.000000,0.000000,6.796095e+05,5.990952e+05,1.324308e+08,2650.000000,2451.000000,2.694938e+06,49334.000000,8.623552e+06,3.088454e+06,2.689327e+06,700440.000000,1.744852e+07,1.651556e+07,1.747048e+07,1.650727e+07,6.331742e+08,1.243162e+07,6.316918e+08,1.238415e+07,4.903424e+07,6.657055e+08
max,1.318654e+19,999.000000,999.000000,1.859336e+06,2.140743e+14,8.823971e+14,9.900120e+13,96923.000000,7120.000000,378160.000000,58613.000000,100.000000,93.000000,100.000000,94.000000,100.000000,98.000000,100.000000,96.000000,1.365365e+08,1.449113e+08,1.859336e+09,604061.000000,604122.000000,3.586064e+06,65870.000000,1.146283e+07,4.121357e+06,3.586146e+06,936418.000000,2.325910e+07,2.201196e+07,2.325919e+07,2.201196e+07,8.434419e+08,1.655879e+07,8.434425e+08,1.655882e+07,7.833131e+07,9.029696e+08

In [25]:
#check skewness of the data
db.skew(axis = 0, skipna = True)

Bearer Id                           0.026666
Start ms                            0.000968
End ms                             -0.001163
Dur. (ms)                           3.952609
IMSI                               41.045956
MSISDN/Number                     332.155856
IMEI                                1.071470
Avg RTT DL (ms)                    62.907828
Avg RTT UL (ms)                    28.457415
Avg Bearer TP DL (kbps)             2.589437
Avg Bearer TP UL (kbps)             4.503413
DL TP < 50 Kbps (%)                -2.297803
50 Kbps < DL TP < 250 Kbps (%)      3.271453
250 Kbps < DL TP < 1 Mbps (%)       4.566158
DL TP > 1 Mbps (%)                  5.370351
UL TP < 10 Kbps (%)                -8.985016
10 Kbps < UL TP < 50 Kbps (%)      10.943888
50 Kbps < UL TP < 300 Kbps (%)     21.878495
UL TP > 300 Kbps (%)               36.174053
Activity Duration DL (ms)           5.872256
Activity Duration UL (ms)           7.382557
Dur. (ms).1                         3.952609
Nb of sec with Vol DL < 6250B       9.042166
Nb of sec with Vol UL < 1250B       7.495176
Social Media DL (Bytes)            -0.002136
Social Media UL (Bytes)            -0.000359
Google DL (Bytes)                  -0.008092
Google UL (Bytes)                   0.002216
Email DL (Bytes)                   -0.002463
Email UL (Bytes)                    0.007358
Youtube DL (Bytes)                  0.000231
Youtube UL (Bytes)                 -0.001142
Netflix DL (Bytes)                 -0.002442
Netflix UL (Bytes)                 -0.000113
Gaming DL (Bytes)                  -0.003460
Gaming UL (Bytes)                  -0.001840
Other DL (Bytes)                    0.001400
Other UL (Bytes)                    0.001392
Total UL (Bytes)                   -0.002456
Total DL (Bytes)                   -0.003153
dtype: float64

We can substitute most of null values as NaN can be changed to value of 0
replacing null values with apprioprate data based on the type the columns.

In [ ]:
# IMSI, MSISDN/Number, Avg RTT DL (ms), Avg RTT UL (ms), UL TP < 10 Kbps (%), 10 Kbps < UL TP < 50 Kbps (%) 
# 50 Kbps < UL TP < 300 Kbps (%), UL TP > 300 Kbps (%) , Nb of sec with Vol DL < 6250B,
# Nb of sec with Vol UL < 1250B
# the above mentioned column more of skew data, fill the the missing value.

In [30]:
db['IMSI'] = db['IMSI'].fillna(db['IMSI'].median())
db['Avg RTT DL (ms)'] = db['Avg RTT DL (ms)'].fillna(db['Avg RTT DL (ms)'].median())
db['Avg RTT UL (ms)'] = db['Avg RTT UL (ms)'].fillna(db['Avg RTT UL (ms)'].median())
db['UL TP < 10 Kbps (%)'] = db['UL TP < 10 Kbps (%)'].fillna(db['UL TP < 10 Kbps (%)'].median())
db['10 Kbps < UL TP < 50 Kbps (%)'] = db['10 Kbps < UL TP < 50 Kbps (%)'].fillna(db['10 Kbps < UL TP < 50 Kbps (%)'].median())
db['50 Kbps < UL TP < 300 Kbps (%)'] = db['50 Kbps < UL TP < 300 Kbps (%)'].fillna(db['50 Kbps < UL TP < 300 Kbps (%)'].median())
db['UL TP > 300 Kbps (%)'] = db['UL TP > 300 Kbps (%)'].fillna(db['UL TP > 300 Kbps (%)'].median())
db['Nb of sec with Vol DL < 6250B'] = db['Nb of sec with Vol DL < 6250B'].fillna(db['Nb of sec with Vol DL < 6250B'].median())
db['Nb of sec with Vol UL < 1250B'] = db['Nb of sec with Vol UL < 1250B'].fillna(db['Nb of sec with Vol UL < 1250B'].median())

In [ ]:
# Bearer Id, IMEI, Last Location Name,DL TP < 50 Kbps (%),UL TP < 10 Kbps (%), 10 Kbps < UL TP < 50 Kbps (%),
# Handset Manufacturer               
# Handset Type                        
# Nb of sec with Vol DL < 6250B       
# Nb of sec with Vol UL < 1250B

In [38]:
db['Bearer Id'] = db['Bearer Id'].fillna(db['Bearer Id'].median())
db['IMEI'] = db['IMEI'].fillna(db['IMEI'].median())
db['Last Location Name'].fillna('Unknown',inplace=True)
db['MSISDN/Number'] = db['MSISDN/Number'].fillna(db['MSISDN/Number'].median())
db['Handset Manufacturer'].fillna('Unknown',inplace=True)
db['Handset Type'].fillna('Unknown',inplace=True)
db['DL TP < 50 Kbps (%)'] = db['DL TP < 50 Kbps (%)'].fillna(db['DL TP < 50 Kbps (%)'].median())
db['UL TP < 10 Kbps (%)'] = db['UL TP < 10 Kbps (%)'].fillna(db['UL TP < 10 Kbps (%)'].median())
db['10 Kbps < UL TP < 50 Kbps (%)'] = db['10 Kbps < UL TP < 50 Kbps (%)'].fillna(db['10 Kbps < UL TP < 50 Kbps (%)'].median())
db['50 Kbps < DL TP < 250 Kbps (%)'] = db['50 Kbps < DL TP < 250 Kbps (%)'].fillna(db['50 Kbps < DL TP < 250 Kbps (%)'].median())
db['250 Kbps < DL TP < 1 Mbps (%)'] = db['250 Kbps < DL TP < 1 Mbps (%)'].fillna(db['250 Kbps < DL TP < 1 Mbps (%)'].median())
db['DL TP > 1 Mbps (%)'] = db['DL TP > 1 Mbps (%)'].fillna(db['DL TP > 1 Mbps (%)'].median())
db['Nb of sec with Vol DL < 6250B'] = db['Nb of sec with Vol DL < 6250B'].fillna(db['Nb of sec with Vol DL < 6250B'].median())
db['Nb of sec with Vol UL < 1250B'] = db['Nb of sec with Vol UL < 1250B'].fillna(db['Nb of sec with Vol UL < 1250B'].median())

In [39]:
db.isnull().sum()

Bearer Id                         0
Start                             1
Start ms                          1
End                               1
End ms                            1
Dur. (ms)                         1
IMSI                              0
MSISDN/Number                     0
IMEI                              0
Last Location Name                0
Avg RTT DL (ms)                   0
Avg RTT UL (ms)                   0
Avg Bearer TP DL (kbps)           1
Avg Bearer TP UL (kbps)           1
DL TP < 50 Kbps (%)               0
50 Kbps < DL TP < 250 Kbps (%)    0
250 Kbps < DL TP < 1 Mbps (%)     0
DL TP > 1 Mbps (%)                0
UL TP < 10 Kbps (%)               0
10 Kbps < UL TP < 50 Kbps (%)     0
50 Kbps < UL TP < 300 Kbps (%)    0
UL TP > 300 Kbps (%)              0
Activity Duration DL (ms)         1
Activity Duration UL (ms)         1
Dur. (ms).1                       1
Handset Manufacturer              0
Handset Type                      0
Nb of sec with Vol DL < 6250B     0
Nb of sec with Vol UL < 1250B     0
Social Media DL (Bytes)           0
Social Media UL (Bytes)           0
Google DL (Bytes)                 0
Google UL (Bytes)                 0
Email DL (Bytes)                  0
Email UL (Bytes)                  0
Youtube DL (Bytes)                0
Youtube UL (Bytes)                0
Netflix DL (Bytes)                0
Netflix UL (Bytes)                0
Gaming DL (Bytes)                 0
Gaming UL (Bytes)                 0
Other DL (Bytes)                  0
Other UL (Bytes)                  0
Total UL (Bytes)                  1
Total DL (Bytes)                  1
dtype: int64

In [40]:
#droping rows which is supposed to have unique value and have null or NaN values
db = db.dropna()

In [41]:
db.isnull().sum()

Bearer Id                         0
Start                             0
Start ms                          0
End                               0
End ms                            0
Dur. (ms)                         0
IMSI                              0
MSISDN/Number                     0
IMEI                              0
Last Location Name                0
Avg RTT DL (ms)                   0
Avg RTT UL (ms)                   0
Avg Bearer TP DL (kbps)           0
Avg Bearer TP UL (kbps)           0
DL TP < 50 Kbps (%)               0
50 Kbps < DL TP < 250 Kbps (%)    0
250 Kbps < DL TP < 1 Mbps (%)     0
DL TP > 1 Mbps (%)                0
UL TP < 10 Kbps (%)               0
10 Kbps < UL TP < 50 Kbps (%)     0
50 Kbps < UL TP < 300 Kbps (%)    0
UL TP > 300 Kbps (%)              0
Activity Duration DL (ms)         0
Activity Duration UL (ms)         0
Dur. (ms).1                       0
Handset Manufacturer              0
Handset Type                      0
Nb of sec with Vol DL < 6250B     0
Nb of sec with Vol UL < 1250B     0
Social Media DL (Bytes)           0
Social Media UL (Bytes)           0
Google DL (Bytes)                 0
Google UL (Bytes)                 0
Email DL (Bytes)                  0
Email UL (Bytes)                  0
Youtube DL (Bytes)                0
Youtube UL (Bytes)                0
Netflix DL (Bytes)                0
Netflix UL (Bytes)                0
Gaming DL (Bytes)                 0
Gaming UL (Bytes)                 0
Other DL (Bytes)                  0
Other UL (Bytes)                  0
Total UL (Bytes)                  0
Total DL (Bytes)                  0
dtype: int64

# top 10 handsets used by the customers

In [42]:
top10Handsets = db.groupby('Handset Type')['Handset Type'].count().nlargest(10)
top10Handsets

Handset Type
Huawei B528S-23A                19752
Apple iPhone 6S (A1688)          9419
Apple iPhone 6 (A1586)           9023
undefined                        8987
Apple iPhone 7 (A1778)           6326
Apple iPhone Se (A1723)          5187
Apple iPhone 8 (A1905)           4993
Apple iPhone Xr (A2105)          4568
Samsung Galaxy S8 (Sm-G950F)     4520
Apple iPhone X (A1901)           3813
Name: Handset Type, dtype: int64

# identify the top 3 handset manufacturers

In [43]:
top3Handset_manufacturer = db.groupby('Handset Manufacturer')['Handset Manufacturer'].count().nlargest(3)
top3Handset_manufacturer

Handset Manufacturer
Apple      59565
Samsung    40839
Huawei     34423
Name: Handset Manufacturer, dtype: int64

# identify the top 5 handsets per handset manufacturer

In [45]:
top5HadsetPerManufacturer = db['Handset Type'].groupby(db['Handset Manufacturer']).apply(lambda x:x.value_counts().head(5)).to_frame()
top5HadsetPerManufacturer

                                                                                                      Handset Type
Handset Manufacturer
A-Link Telecom International Co Limited           A-Link Telecom I. Cubot X18 Plus                               2
                                                  A-Link Telecom I. Cubot R9                                     1
                                                  A-Link Telecom I. Cubot Note Plus                              1
                                                  A-Link Telecom I. Cubot A5                                     1
                                                  A-Link Telecom I. Cubot Note S                                 1
ASUSTeK                                           Asustek Asus Zb552Kl Zenfone Go                                7
                                                  Asustek Asus Zenfone2 Laser Ze600Kl                            5
                                                  Asustek Asus Zenfone2 Laser Ze601Kl                            4
                                                  Asustek Asus Zenfone 2 Laser Ze500Kl                           3
                                                  Asustek Asus Zenfone Selfie Zd551Kl                            2
Acer                                              Acer M310                                                      5
                                                  Acer Liquid Zest Plus                                          2
                                                  Acer Liquid M220                                               1
                                                  Acer Liquid Z630                                               1
                                                  Acer Liquid Z530                                               1
Adar                                              Adar Stanley Mobile S231                                       1
Alif Communications                               Alif Communicati. Pulian Cm84                                  1
Apple                                             Apple iPhone 6S (A1688)                                     9419
                                                  Apple iPhone 6 (A1586)                                      9023
                                                  Apple iPhone 7 (A1778)                                      6326
                                                  Apple iPhone Se (A1723)                                     5187
                                                  Apple iPhone 8 (A1905)                                      4993
Archos SA                                         Archos Sa Archos 50C Platinum                                  1
                                                  Archos Sa Archos 40 Helium                                     1
                                                  Archos Sa Diamond S                                            1
                                                  Archos Sa 50 Cesium                                            1
                                                  Archos Sa Archos 45B Helium 50B Helium 50C Heli...             1
Archos Sa                                         Archos Sa 55 Helium (Ultra)                                    8
                                                  Archos Sa 50 Saphir                                            8
                                                  Archos Sa Access 45 4G                                         5
...                                                                                                            ...
Wiko Global Sasu                                  Wiko Global Sasu Wiko Rainbow Lite 4G                         44
                                                  Wiko Global Sasu Wiko Sunny                                   34
Wileyfox Europe Limited                           Wileyfox Europe. Wileyfox Swift 2                              2
                                                  Wileyfox Europe. Wileyfox Spark                                1
Wistron                                           Wistron M18Qw                                                  2
                                                  Wistron Wnc D18Qx                                              2
Xiaomi Communications Co Ltd                      Xiaomi Communica. Redmi Note5                                140
                                                  Xiaomi Communica. Mi A2                                       18
                                                  Xiaomi Communica. Pocophone F1                                17
                                                  Xiaomi Communica. Mi 8                                        17
                                                  Xiaomi Communica. Redmi 4X                                    17
Yi Sheng Technology International (Hk) Co Limited Yi Sheng Technol. Gretel A7                                    1
Yop Technology Co Limited                         Yop Technology C. Maze Alpha                                   1
Yota Devices                                      Yota Devices Yota Y3                                           1
                                                  Yota Devices Yotaphone2                                        1
ZTE                                               Zte A2016                                                      2
                                                  Zte Blade A452 Blade A452                                      1
Zebra Technologies Corp.                          Zebra Technologi. Symbol Tc55Bh                                8
                                                  Zebra Technologi. Mc659B                                       4
                                                  Zebra Technologi. Mc67Na                                       1
                                                  Zebra Technologi. Mc5574                                       1
Zte                                               Zte Mf259                                                    170
                                                  Zte Racer Iii Mini Zte Switch X1 Bouygues Telec...             5
                                                  Zte Blade V7 Lite Blade V6 Plus Zte Blitz                      3
                                                  Zte Zte Blade C2 Smartphone Android By Sfr Star...             2
                                                  Zte Blade A506 Blade A506                                      1
ZyXEL Communications Corp                         Zyxel Communicat. Zyxel Wah7706                                1
Zyxel Communications Corp                         Zyxel Communicat. Sbg3600                                      1
                                                  Zyxel Communicat. Lte7460                                      1
undefined                                         undefined                                                   8987

[435 rows x 1 columns]

# Task 1

# Task 1.1

# Number of xDR sessions per user

In [48]:
db.groupby(['Bearer Id'])['Bearer Id'].count()

Bearer Id
6.917538e+18    1
6.917538e+18    1
6.917538e+18    1
6.917538e+18    1
6.917538e+18    1
6.917538e+18    1
6.917538e+18    1
6.917538e+18    1
6.917538e+18    1
6.917538e+18    1
6.917538e+18    1
6.917538e+18    1
6.917538e+18    2
6.917538e+18    1
6.917538e+18    1
6.917538e+18    1
6.917538e+18    1
6.917538e+18    1
6.917538e+18    1
6.917538e+18    1
6.917538e+18    1
6.917538e+18    1
6.917538e+18    1
6.917538e+18    1
6.917538e+18    1
6.917538e+18    1
6.917538e+18    1
6.917538e+18    1
6.917538e+18    1
6.917538e+18    1
               ..
1.318654e+19    1
1.318654e+19    1
1.318654e+19    1
1.318654e+19    1
1.318654e+19    1
1.318654e+19    1
1.318654e+19    1
1.318654e+19    1
1.318654e+19    1
1.318654e+19    1
1.318654e+19    1
1.318654e+19    1
1.318654e+19    1
1.318654e+19    1
1.318654e+19    1
1.318654e+19    1
1.318654e+19    1
1.318654e+19    1
1.318654e+19    1
1.318654e+19    1
1.318654e+19    1
1.318654e+19    1
1.318654e+19    1
1.318654e+19    2
1.318654e+19    1
1.318654e+19    1
1.318654e+19    1
1.318654e+19    1
1.318654e+19    1
1.318654e+19    1
Name: Bearer Id, Length: 134709, dtype: int64

# Session duration

In [50]:
#Session duration for each user in milliseconds
db.groupby(['Bearer Id'])['Dur. (ms)'].sum()

Bearer Id
6.917538e+18     24534.0
6.917538e+18     21489.0
6.917538e+18     27786.0
6.917538e+18     15635.0
6.917538e+18     24264.0
6.917538e+18     15548.0
6.917538e+18     20701.0
6.917538e+18     12604.0
6.917538e+18     61431.0
6.917538e+18     18800.0
6.917538e+18     10263.0
6.917538e+18      9860.0
6.917538e+18    321162.0
6.917538e+18    256849.0
6.917538e+18      8604.0
6.917538e+18     15273.0
6.917538e+18      9224.0
6.917538e+18     12934.0
6.917538e+18     14085.0
6.917538e+18     33113.0
6.917538e+18     11823.0
6.917538e+18     19030.0
6.917538e+18     18070.0
6.917538e+18     15494.0
6.917538e+18     14467.0
6.917538e+18     10236.0
6.917538e+18     62446.0
6.917538e+18     22031.0
6.917538e+18     15441.0
6.917538e+18     32313.0
                  ...
1.318654e+19     50019.0
1.318654e+19     47650.0
1.318654e+19     46520.0
1.318654e+19     49376.0
1.318654e+19     54363.0
1.318654e+19     43052.0
1.318654e+19     42697.0
1.318654e+19     64554.0
1.318654e+19     45262.0
1.318654e+19     34897.0
1.318654e+19     40845.0
1.318654e+19     36811.0
1.318654e+19     34170.0
1.318654e+19     38889.0
1.318654e+19     48143.0
1.318654e+19     31901.0
1.318654e+19     31951.0
1.318654e+19     36594.0
1.318654e+19    141081.0
1.318654e+19    140188.0
1.318654e+19    128680.0
1.318654e+19     86399.0
1.318654e+19     80273.0
1.318654e+19    210111.0
1.318654e+19     86401.0
1.318654e+19     80024.0
1.318654e+19    145291.0
1.318654e+19     86399.0
1.318654e+19     86399.0
1.318654e+19    103113.0
Name: Dur. (ms), Length: 134709, dtype: float64

# the total download (DL) and upload (UL) data per user

In [51]:
db.groupby(['Bearer Id'])['Total DL (Bytes)','Total UL (Bytes)'].sum()

              Total DL (Bytes)  Total UL (Bytes)
Bearer Id
6.917538e+18      5.007220e+08        41704610.0
6.917538e+18      7.095493e+08        38693596.0
6.917538e+18      8.544659e+08        15548926.0
6.917538e+18      8.257865e+08        49605688.0
6.917538e+18      6.249578e+08        21983463.0
6.917538e+18      5.721995e+08        47281374.0
6.917538e+18      7.361892e+08        26136298.0
6.917538e+18      8.366814e+08        50633950.0
6.917538e+18      9.013464e+07        38752753.0
6.917538e+18      3.943037e+08        43536988.0
6.917538e+18      1.137449e+08        55776596.0
6.917538e+18      8.116303e+08        40359773.0
6.917538e+18      8.395617e+08       103530280.0
6.917538e+18      4.984038e+08        49685376.0
6.917538e+18      6.640279e+08        39878416.0
6.917538e+18      7.073922e+08        34622972.0
6.917538e+18      7.821276e+08        49890728.0
6.917538e+18      3.379022e+07        44531802.0
6.917538e+18      5.054565e+08        28555201.0
6.917538e+18      1.573172e+08        48491313.0
6.917538e+18      5.549693e+08        35105617.0
6.917538e+18      3.705157e+07        54010973.0
6.917538e+18      6.856240e+08        27139517.0
6.917538e+18      3.733423e+08        54618160.0
6.917538e+18      7.583720e+07        44757242.0
6.917538e+18      4.805957e+08        43997881.0
6.917538e+18      7.979955e+08        60968335.0
6.917538e+18      5.762299e+08        32659912.0
6.917538e+18      6.485637e+08        38864641.0
6.917538e+18      4.889826e+08        24948543.0
...                        ...               ...
1.318654e+19      4.734391e+08        56009975.0
1.318654e+19      6.252267e+08        34642948.0
1.318654e+19      1.715049e+08        51041655.0
1.318654e+19      4.939478e+07        61766135.0
1.318654e+19      9.917738e+07        63246024.0
1.318654e+19      1.238010e+08        35634867.0
1.318654e+19      7.444453e+08        50471531.0
1.318654e+19      4.737893e+08        38479560.0
1.318654e+19      8.154921e+08        52384400.0
1.318654e+19      1.778124e+08        34088881.0
1.318654e+19      5.866610e+08        42255034.0
1.318654e+19      4.487779e+08        50753618.0
1.318654e+19      7.697698e+08        41335416.0
1.318654e+19      4.793054e+08        47635623.0
1.318654e+19      5.139067e+07        31252135.0
1.318654e+19      4.050147e+08        35264327.0
1.318654e+19      3.327510e+08        43419294.0
1.318654e+19      2.678346e+08        54407426.0
1.318654e+19      5.244246e+08        38277671.0
1.318654e+19      5.512121e+08        18973963.0
1.318654e+19      6.072856e+08        60250500.0
1.318654e+19      4.866189e+08        32743279.0
1.318654e+19      3.818779e+08        21494233.0
1.318654e+19      1.161082e+09       100193462.0
1.318654e+19      7.906938e+08        56102807.0
1.318654e+19      1.452931e+08        35412664.0
1.318654e+19      3.870016e+08        36189587.0
1.318654e+19      8.726888e+08        35919460.0
1.318654e+19      3.863551e+08        40877676.0
1.318654e+19      3.272128e+08        46147558.0

[134709 rows x 2 columns]